In [27]:
import warnings
warnings.filterwarnings("ignore")

In [1]:
import pandas as pd

In [39]:
data=pd.read_csv(r"C:\Users\Nandani\Downloads\Ecommerce_Mock_Test_Data.csv")

In [40]:
data.shape

(2000, 15)

In [41]:
data.isnull().sum()

Customer_ID             0
Age                   142
Gender                  0
City                    0
Membership_Type         0
Signup_Year           347
Product_Category        0
Quantity                0
Price_Per_Unit          0
Discount_Percent        0
Payment_Method          0
Delivery_Time_Days      0
Rating                  0
Returned                0
Total_Amount            0
dtype: int64

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Customer_ID         2000 non-null   int64  
 1   Age                 1858 non-null   float64
 2   Gender              2000 non-null   object 
 3   City                2000 non-null   object 
 4   Membership_Type     2000 non-null   object 
 5   Signup_Year         1653 non-null   float64
 6   Product_Category    2000 non-null   object 
 7   Quantity            2000 non-null   int64  
 8   Price_Per_Unit      2000 non-null   int64  
 9   Discount_Percent    2000 non-null   int64  
 10  Payment_Method      2000 non-null   object 
 11  Delivery_Time_Days  2000 non-null   int64  
 12  Rating              2000 non-null   float64
 13  Returned            2000 non-null   object 
 14  Total_Amount        2000 non-null   float64
dtypes: float64(4), int64(5), object(6)
memory usage: 234.5+

In [43]:
data.duplicated().sum()

np.int64(0)

In [44]:
data["Age"].unique()

array([53., 66., 43., 29., 57., 22., 35., 72., 33., 37., 25., 38., 67.,
       nan, 54., 17., 36., 16., 58., 44., 52., 74., 47., 26., 39., 63.,
       41., 73., 56., 42., 30., 65., 69., 71., 51., 23., 32., 18., 28.,
       64., 40., 61., 21., 49., 31., 50., 20., 68., 48., 24., 45., 62.,
       59., 55., 15., 19., 27., 46., 34., 70., 60.])

In [45]:
data["Age"]=data["Age"].fillna(data["Age"].median())

In [46]:
data["Age"].unique()

array([53., 66., 43., 29., 57., 22., 35., 72., 33., 37., 25., 38., 67.,
       46., 54., 17., 36., 16., 58., 44., 52., 74., 47., 26., 39., 63.,
       41., 73., 56., 42., 30., 65., 69., 71., 51., 23., 32., 18., 28.,
       64., 40., 61., 21., 49., 31., 50., 20., 68., 48., 24., 45., 62.,
       59., 55., 15., 19., 27., 34., 70., 60.])

In [47]:
data = data[(data['Age'] >= 18) & (data['Age'] <= 70)]

In [48]:
data["Age"].unique()

array([53., 66., 43., 29., 57., 22., 35., 33., 37., 25., 38., 67., 46.,
       54., 36., 58., 44., 52., 47., 26., 39., 63., 41., 56., 42., 30.,
       65., 69., 51., 23., 32., 18., 28., 64., 40., 61., 21., 49., 31.,
       50., 20., 68., 48., 24., 45., 62., 59., 55., 19., 27., 34., 70.,
       60.])

In [49]:
data["Signup_Year"].mode()

0    2016.0
Name: Signup_Year, dtype: float64

In [50]:
data["Signup_Year"]=data["Signup_Year"].fillna(data["Signup_Year"].mode()[0])

In [51]:
data.isnull().sum()

Customer_ID           0
Age                   0
Gender                0
City                  0
Membership_Type       0
Signup_Year           0
Product_Category      0
Quantity              0
Price_Per_Unit        0
Discount_Percent      0
Payment_Method        0
Delivery_Time_Days    0
Rating                0
Returned              0
Total_Amount          0
dtype: int64

In [52]:
data["Signup_Year"]=data["Signup_Year"].astype(int)

In [53]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1775 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Customer_ID         1775 non-null   int64  
 1   Age                 1775 non-null   float64
 2   Gender              1775 non-null   object 
 3   City                1775 non-null   object 
 4   Membership_Type     1775 non-null   object 
 5   Signup_Year         1775 non-null   int64  
 6   Product_Category    1775 non-null   object 
 7   Quantity            1775 non-null   int64  
 8   Price_Per_Unit      1775 non-null   int64  
 9   Discount_Percent    1775 non-null   int64  
 10  Payment_Method      1775 non-null   object 
 11  Delivery_Time_Days  1775 non-null   int64  
 12  Rating              1775 non-null   float64
 13  Returned            1775 non-null   object 
 14  Total_Amount        1775 non-null   float64
dtypes: float64(3), int64(6), object(6)
memory usage: 221.9+ KB


In [54]:
data["Gender"]=data["Gender"].str.strip().str.title()

In [55]:
data["City"]=data["City"].str.strip().str.title()

In [56]:
data["City"].unique()

array(['Mumbai', 'Bangalore', 'Ahmedabad', 'Delhi'], dtype=object)

In [57]:
data["Gender"].unique()

array(['Female', 'Male'], dtype=object)

In [58]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1775 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Customer_ID         1775 non-null   int64  
 1   Age                 1775 non-null   float64
 2   Gender              1775 non-null   object 
 3   City                1775 non-null   object 
 4   Membership_Type     1775 non-null   object 
 5   Signup_Year         1775 non-null   int64  
 6   Product_Category    1775 non-null   object 
 7   Quantity            1775 non-null   int64  
 8   Price_Per_Unit      1775 non-null   int64  
 9   Discount_Percent    1775 non-null   int64  
 10  Payment_Method      1775 non-null   object 
 11  Delivery_Time_Days  1775 non-null   int64  
 12  Rating              1775 non-null   float64
 13  Returned            1775 non-null   object 
 14  Total_Amount        1775 non-null   float64
dtypes: float64(3), int64(6), object(6)
memory usage: 221.9+ KB


In [60]:
data["total"]=data["Quantity"]*data["Price_Per_Unit"]*(1-data["Discount_Percent"]/100)

In [61]:
data["Total_Amount"]==data["total"]

0        True
1        True
2       False
3        True
4        True
        ...  
1995    False
1996     True
1997     True
1998     True
1999     True
Length: 1775, dtype: bool

In [62]:
data["Total_Amount"]=data["total"]

In [64]:
data.drop("total",axis=1,inplace=True)

In [66]:
def Age_Group(x):
    if x >=18 and x <= 25:
        return "Young"
    elif x >=26 and x <= 45:
        return "Adult"
    else:
        return "Senior"

data["Age_Group"]=data["Age"].apply(Age_Group)

In [67]:
data["Age_Group"]

0       Senior
1       Senior
2        Adult
3        Adult
4       Senior
         ...  
1995    Senior
1996     Adult
1997    Senior
1998    Senior
1999    Senior
Name: Age_Group, Length: 1775, dtype: object

In [68]:
data["Total_Amount"]

0       4573.00
1       4692.60
2        130.05
3       2858.40
4       2308.80
         ...   
1995    3702.15
1996     685.10
1997     571.00
1998     682.10
1999    4176.90
Name: Total_Amount, Length: 1775, dtype: float64

In [70]:
def Revenue_Category(x):
    if x < 1000:
        return "Low"
    elif x >= 1000 and x <= 4000:
        return "Medium"
    else:
        return "High"

data["Revenue_Category"]=data["Total_Amount"].apply(Revenue_Category)

In [71]:
data["Revenue_Category"]

0         High
1         High
2          Low
3       Medium
4       Medium
         ...  
1995    Medium
1996       Low
1997       Low
1998       Low
1999      High
Name: Revenue_Category, Length: 1775, dtype: object

In [72]:
import numpy as np

In [75]:
data["Log_Total_Amount"]=np.log1p(data["Total_Amount"])

In [76]:
data["Log_Total_Amount"]

0       8.428143
1       8.453955
2       4.875579
3       7.958367
4       7.744916
          ...   
1995    8.216939
1996    6.531023
1997    6.349139
1998    6.526641
1999    8.337564
Name: Log_Total_Amount, Length: 1775, dtype: float64

In [82]:
data[["Customer_ID","Age","Age_Group","Gender","City","Membership_Type","Signup_Year","Revenue_Category"]].to_csv("Customer_Info1.csv",index=False)

In [80]:
data[["Customer_ID","Product_Category","Quantity","Price_Per_Unit","Discount_Percent","Total_Amount","Log_Total_Amount","Payment_Method","Delivery_Time_Days","Rating","Returned"]].to_csv("Transaction_Data.csv",index=False)

In [81]:
data.to_csv("clean_ecommer.csv",index=False)